# *Intelligent Course Suggester*
___

>*Helping people enrich their user profiles by recommending the relevant courses to up their game.*

In [3]:
#Classification with Collaborative Filtering
#using Logistic Regression
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

from pandas import Series, DataFrame
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import  classification_report

## Dataset
The dataset can be acquired from LinkedIN profiles or and Other Website which maintains profiles that include 
- affinity scores to various skills honed by the user
- education level thresholded to range [1,3] where
    * 1 Bachelor's degree
    * 2 Master's degree
    * 3 Postgraduate's degree
- Position in Workplace thresholded to range [0,3] where
    * 0 fresher
    * 1 junior employee
    * 2 senior employee
    * 3 manager
- list of courses taken up by the user

#### Affinity scores
Affinity profiling centers on creating weighted scores for users.
These scores are calculated and assigned by measuring the correlation between user skills and the courses taken.
It can also take into account the level of interest for the particular skill.

Including affinity provides a multidimentional feature space for understanding the behavior of the users.

In [4]:
linked_full=pd.read_csv('dataset.csv')
linked_full.head()

,Person ID,S_Excel,S_R,S_Tableu,S_Sql,S_Android,S_Python,S_java,S_Seom,S_Smom,...,C_webdevfront,C_webback,C_photoshop,C_Illustrator,C_DigitalMarketing,C_Webanalytics,C_networksimul,C_cryptography,C_CCNA,C_CDNA
0,10001,0.4,0.3,0.2,0.0,0.9,0.7,0.9,0.1,0.1,...,0,0,1,0,0,0,0,0,1,0
1,10002,0.3,0.2,0.1,0.3,0.3,0.4,0.5,0.2,0.3,...,0,0,0,0,0,0,1,0,0,0
2,10003,0.9,0.5,0.1,0.7,0.3,0.1,0.1,0.8,0.3,...,0,0,0,0,0,0,0,0,0,0
3,10004,0.4,0.2,0.3,0.4,0.5,0.9,0.5,0.5,0.4,...,0,0,0,0,0,0,0,0,0,0
4,10005,0.3,0.2,0.0,0.4,0.2,0.1,0.1,0.3,0.1,...,1,0,0,0,0,0,0,0,0,0

### Attributes
- All the attributes starting with S_ stand for skill in the following attribute name.
 and the ones starting with C_ stand for the course for the particular attribute name.
 i.e, S_Excel stands for Skill in Excel
 and C_Excel stands for Course for Learning Excel.
- Level stands for Position in Workplace
- Education stands for Education level

In [5]:
linked_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 38 columns):
Person ID             100 non-null int64
S_Excel               100 non-null float64
S_R                   100 non-null float64
S_Tableu              100 non-null float64
S_Sql                 100 non-null float64
S_Android             100 non-null float64
S_Python              100 non-null float64
S_java                100 non-null float64
S_Seom                100 non-null float64
S_Smom                100 non-null float64
S_CNOperation         100 non-null float64
S_Ndesign             100 non-null float64
S_NetworkSecurity     100 non-null float64
S_Photoshop           100 non-null float64
S_Illustrator         100 non-null float64
S_css                 100 non-null float64
S_Php                 100 non-null float64
S_js                  100 non-null float64
S_html                100 non-null float64
Level                 100 non-null int64
Education             100 non-null int64
C_advexcel            100 non-null int64
C_R                   100 non-null int64
C_tableu              100 non-null int64
C_Sql                 100 non-null int64
C_Android             100 non-null int64
C_java                100 non-null int64
C_python              100 non-null int64
C_webdevfront         100 non-null int64
C_webback             100 non-null int64
C_photoshop           100 non-null int64
C_Illustrator         100 non-null int64
C_DigitalMarketing    100 non-null int64
C_Webanalytics        100 non-null int64
C_networksimul        100 non-null int64
C_cryptography        100 non-null int64
C_CCNA                100 non-null int64
C_CDNA                100 non-null int64
dtypes: float64(18), int64(20)
memory usage: 29.8 KB

### Spilting the dataset into train and test

In [6]:
train,test =train_test_split(linked_full,test_size=0.4)

In [8]:
z=35
X=train.ix[:,(1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21)].values

y=train.ix[:,z].values

X

array([[ 0.2,  0.2,  0. , ...,  2. ,  3. ,  0. ],
       [ 0.3,  0.4,  0.1, ...,  2. ,  2. ,  0. ],
       [ 0.2,  0.6,  0.4, ...,  0. ,  3. ,  0. ],
       ...,
       [ 0.3,  0.4,  0. , ...,  0. ,  2. ,  0. ],
       [ 0.7,  0.3,  0. , ...,  1. ,  2. ,  1. ],
       [ 0.3,  0. ,  0. , ...,  2. ,  3. ,  0. ]])

### Classification based Collaborative filtering using Logistic Regression

Logistic regression is used to describe data and to explain the relationship between one dependent binary variable and one or more nominal, ordinal, interval or ratio-level independent variables.

In this model, the logit of the probability of relevance of a term is modeled as a linear function of
the feature values. The model is trained using maximum likelihood.


The Collaborative filtering here calculates the similarity between different person ids which is used as another parameter in the recommendation system.
This aspect allows us to overcome the coldstart problem i.e, when we donot have enough data available for a new person.

In [12]:
LogReg = LogisticRegression()
LogReg.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

### Testing

The dataset seperated for testing is provided as input to the trained model.

The output shows the accuracy rates for the recommendation for every course consider along with a list of person ids to whom the course was suggested.

In [11]:
for z in range(21,38):
    X=train.ix[:,(1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20)].values
    y=train.ix[:,z].values
    LogReg = LogisticRegression()
    LogReg.fit(X, y)
    X=test.ix[:,(1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20)].values
    y_pred = LogReg.predict(X)
    #print(y_pred)
    colname=train.columns[z]
    print("Suggested Course:")
    print("\t",colname)
    i=0;
    print("Person id:")
    for x in test.ix[:,0] :
        if (y_pred[i]==1):
            print("\t",x,end=",")
        i+=1
    print("\n")
    y=test.ix[:,z].values
    print(classification_report(y,y_pred))
    print("#"*60)

Suggested Course:
	 C_advexcel
Person id:
	 10018,	 10042,	 10072,

             precision    recall  f1-score   support

          0       0.59      0.96      0.73        23
          1       0.67      0.12      0.20        17

avg / total       0.63      0.60      0.51        40

############################################################
Suggested Course:
	 C_R
Person id:
	 10054,	 10076,	 10071,

             precision    recall  f1-score   support

          0       0.81      0.97      0.88        31
          1       0.67      0.22      0.33         9

avg / total       0.78      0.80      0.76        40

############################################################
Suggested Course:
	 C_tableu
Person id:
	 10063,	 10098,	 10052,	 10021,

             precision    recall  f1-score   support

          0       0.83      0.94      0.88        32
          1       0.50      0.25      0.33         8

avg / total       0.77      0.80      0.77        40

############################################################
Suggested Course:
	 C_Sql
Person id:
	 10055,	 10060,

             precision    recall  f1-score   support

          0       0.76      0.94      0.84        31
          1       0.00      0.00      0.00         9

avg / total       0.59      0.72      0.65        40

############################################################
Suggested Course:
	 C_Android
Person id:


             precision    recall  f1-score   support

          0       0.93      1.00      0.96        37
          1       0.00      0.00      0.00         3

avg / total       0.86      0.93      0.89        40

############################################################
Suggested Course:
	 C_java
Person id:
	 10088,

             precision    recall  f1-score   support

          0       0.72      1.00      0.84        28
          1       1.00      0.08      0.15        12

avg / total       0.80      0.72      0.63        40

############################################################
Suggested Course:
	 C_python
Person id:
	 10087,	 10065,

             precision    recall  f1-score   support

          0       0.82      0.97      0.89        32
          1       0.50      0.12      0.20         8

avg / total       0.75      0.80      0.75        40

############################################################
Suggested Course:
	 C_webdevfront
Person id:


             precision    recall  f1-score   support

          0       0.88      1.00      0.93        35
          1       0.00      0.00      0.00         5

avg / total       0.77      0.88      0.82        40

############################################################
Suggested Course:
	 C_webback
Person id:


             precision    recall  f1-score   support

          0       0.93      1.00      0.96        37
          1       0.00      0.00      0.00         3

avg / total       0.86      0.93      0.89        40

############################################################
Suggested Course:
	 C_photoshop
Person id:
	 10058,	 10065,	 10060,	 10075,

             precision    recall  f1-score   support

          0       0.78      0.90      0.84        31
          1       0.25      0.11      0.15         9

avg / total       0.66      0.72      0.68        40

############################################################
Suggested Course:
	 C_Illustrator
Person id:


             precision    recall  f1-score   support

          0       0.82      1.00      0.90        33
          1       0.00      0.00      0.00         7

avg / total       0.68      0.82      0.75        40

############################################################
Suggested Course:
	 C_DigitalMarketing
Person id:


             precision    recall  f1-score   support

          0       0.97      1.00      0.99        39
          1       0.00      0.00      0.00         1

avg / total       0.95      0.97      0.96        40

############################################################
Suggested Course:
	 C_Webanalytics
Person id:


             precision    recall  f1-score   support

          0       0.97      1.00      0.99        39
          1       0.00      0.00      0.00         1

avg / total       0.95      0.97      0.96        40

############################################################
Suggested Course:
	 C_networksimul
Person id:


             precision    recall  f1-score   support

          0       0.95      1.00      0.97        38
          1       0.00      0.00      0.00         2

avg / total       0.90      0.95      0.93        40

############################################################
Suggested Course:
	 C_cryptography
Person id:


             precision    recall  f1-score   support

          0       0.82      1.00      0.90        33
          1       0.00      0.00      0.00         7

avg / total       0.68      0.82      0.75        40

############################################################
Suggested Course:
	 C_CCNA
Person id:
	 10077,

             precision    recall  f1-score   support

          0       0.90      1.00      0.95        35
          1       1.00      0.20      0.33         5

avg / total       0.91      0.90      0.87        40

############################################################
Suggested Course:
	 C_CDNA
Person id:
	 10077,

             precision    recall  f1-score   support

          0       0.87      1.00      0.93        34
          1       1.00      0.17      0.29         6

avg / total       0.89      0.88      0.83        40

############################################################